// constants of fetchAppointmentsByMonth
export const FETCH_MONTH_APPOINTMENTS_INIT = 'FETCH_MONTH_APPOINTMENTS_INIT';
export const FETCH_MONTH_APPOINTMENTS_SUCCESS =
  'FETCH_MONTH_APPOINTMENTS_SUCCESS';
export const FETCH_MONTH_APPOINTMENTS_FAILURE =
  'FETCH_MONTH_APPOINTMENTS_FAILURE';
export const SET_SELECTED_MONTH = 'SET_SELECTED_MONTH';
export const SET_PROFESSIONAL_IDS = 'SET_PROFESSIONAL_IDS';
export const FILTER_SCHEDULES = 'FILTER_SCHEDULES';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const FETCH_CURRENT_MONTH_APPOINTMENTS =
  'FETCH_CURRENT_MONTH_APPOINTMENTS';

// constants for fetchPlacesAndProfessionals
export const FETCH_PLACES_PROFESSIONALS_INIT =
  'FETCH_PLACES_PROFESSIONALS_INIT';
export const FETCH_PLACES_PROFESSIONALS_SUCCESS =
  'FETCH_PLACES_PROFESSIONALS_SUCCESS';
export const FETCH_PLACES_PROFESSIONALS_FAILURE =
  'FETCH_PLACES_PROFESSIONALS_FAILURE';
export const FETCH_PLACES_AND_PROFESSIONALS = 'FETCH_PLACES_AND_PROFESSIONALS';

// constants for fetchAppointmentById
export const FETCH_APPOINTMENT_INIT = 'FETCH_APPOINTMENT_INIT';
export const FETCH_APPOINTMENT_SUCCESS = 'FETCH_APPOINTMENT_SUCCESS';
export const FETCH_APPOINTMENT_FAILURE = 'FETCH_APPOINTMENT_FAILURE';
export const FETCH_APPOINTMENT_BY_ID = 'FETCH_APPOINTMENT_BY_ID';
export const UPDATE_FETCHED_APPOINTMENT = 'UPDATE_FETCHED_APPOINTMENT';
export const ADD_APPOINTMENT_TO_CACHE = 'ADD_APPOINTMENT_TO_CACHE';
export const SET_PROFESSIONAL_ID_AND_NAME = 'SET_PROFESSIONAL_ID_AND_NAME';

// constants for visibility context
export const SHOW_EDIT_MODAL = 'SHOW_EDIT_MODAL';
export const SHOW_CREATE_MODAL = 'SHOW_CREATE_MODAL';
export const SHOW_EVENT_MODAL = 'SHOW_EVENT_MODAL';

// constants for color context
export const SET_COLORS = 'SET_COLORS';
export const SET_COLOR_INDEX = 'SET_COLOR_INDEX';
export const SET_COLOR_ASSIGNMENT = 'SET_COLOR_ASSIGNMENT';

// constants for fetchEmails
export const FETCH_EMAILS_INIT = 'FETCH_EMAILS_INIT';
export const FETCH_EMAILS_SUCCESS = 'FETCH_EMAILS_SUCCESS';
export const FETCH_EMAILS_FAILURE = 'FETCH_EMAILS_FAILURE';
export const FETCH_EMAILS = 'FETCH_EMAILS';
export const SET_QUERY = 'SET_QUERY';

// constants for fetchNames
export const FETCH_NAMES_INIT = 'FETCH_NAMES_INIT';
export const FETCH_NAMES_SUCCESS = 'FETCH_NAMES_SUCCESS';
export const FETCH_NAMES_FAILURE = 'FETCH_NAMES_FAILURE';
export const FETCH_NAMES = 'FETCH_NAMES';
export const SET_NAME = 'SET_NAME';

// constants for fetchUserByEmail
export const FETCH_USER_INIT = 'FETCH_USER_INIT';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE';
export const FETCH_USER = 'FETCH_USER';
export const SET_EMAIL_AND_CALLBACK = 'SET_EMAIL_AND_CALLBACK';

// constants for createAppointment
export const CREATE_APPOINTMENT_INIT = 'CREATE_APPOINTMENT_INIT';
export const CREATE_APPOINTMENT_SUCCESS = 'CREATE_APPOINTMENT_SUCCESS';
export const CREATE_APPOINTMENT_FAILURE = 'CREATE_APPOINTMENT_FAILURE';
export const CREATE_APPOINTMENT = 'CREATE_APPOINTMENT';
export const SET_SUBMITTER_AND_DATA = 'SET_SUBMITTER_AND_DATA';

// constants for updateAppointment
export const UPDATE_APPOINTMENT_INIT = 'UPDATE_APPOINTMENT_INIT';
export const UPDATE_APPOINTMENT_SUCCESS = 'UPDATE_APPOINTMENT_SUCCESS';
export const UPDATE_APPOINTMENT_FAILURE = 'UPDATE_APPOINTMENT_FAILURE';
export const UPDATE_APPOINTMENT = 'UPDATE_APPOINTMENT';
export const SET_UPDATE_SUBMITTER_AND_DATA = 'SET_UPDATE_SUBMITTER_AND_DATA';
