// constants of fetchAppointmentsByMonth
export const FETCH_MONTH_APPOINTMENTS_INIT = 'FETCH_MONTH_APPOINTMENTS_INIT';
export const FETCH_MONTH_APPOINTMENTS_SUCCESS =
  'FETCH_MONTH_APPOINTMENTS_SUCCESS';
export const FETCH_MONTH_APPOINTMENTS_FAILURE =
  'FETCH_MONTH_APPOINTMENTS_FAILURE';
export const SET_SELECTED_MONTH = 'SET_SELECTED_MONTH';
export const SET_PROFESSIONAL_IDS = 'SET_PROFESSIONAL_IDS';
export const FILTER_SCHEDULES = 'FILTER_SCHEDULES';
export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const UPDATE_SCHEDULE = 'UPDATE_SCHEDULE';
export const DELETE_SCHEDULE = 'DELETE_SCHEDULE';
export const FETCH_CURRENT_MONTH_APPOINTMENTS =
  'FETCH_CURRENT_MONTH_APPOINTMENTS';
