export const APPOINTMENTS_FETCH = 'APPOINTMENTS_FETCH';
export const APPOINTMENTS_ADD = 'APPOINTMENTS_ADD';
export const APPOINTMENTS_FETCH_ERROR = 'APPOINTMENTS_FETCH_ERROR';
export const MONTHLY_APPOINTMENTS_FETCH = 'MONTHLY_APPOINTMENTS_FETCH';
export const MONTHLY_APPOINTMENTS_ADD = 'MONTHLY_APPOINTMENTS_ADD';
export const MONTHLY_APPOINTMENTS_FETCH_ERROR =
  'MONTHLY_APPOINTMENTS_FETCH_ERROR';
